# ---------------------------------------
# GET reel

###
# This should work
GET http://localhost:3001/api/reel/642c809acc4f71a6f5a1bf14 HTTP/1.1

###
# This should not work
GET http://localhost:3001/api/reel/641c652ag8d3a78c3e33192e HTTP/1.1

# ---------------------------------------
# GET reels

###
# This should work
GET http://localhost:3001/api/reels?ids=642c809acc4f71a6f5a1bf14,642c809acc4f71a6f5a1bf15 HTTP/1.1

###
# This should not work
GET http://localhost:3001/api/reels?ids=641c65a8d3a78c3e33192e,6421d5ba5486ad1885412d07 HTTP/1.1

###
# This should not work
GET http://localhost:3001/api/reels?ids=[] HTTP/1.1

# ---------------------------------------
# POST reel

###
#This should work
POST http://localhost:3001/api/reel HTTP/1.1
content-type: application/json

{
    "gsm": 120,
    "size": 20,
    "shipment": "6412097ce444f65477d71f25",
    "shade": "white",
    "annotations": "Very new",
    "bf": 22,
    "sold": false,
    "soldTo": ""
}

###
#This should not work
POST http://localhost:3001/api/reel HTTP/1.1
content-type: application/json

{
    "gsm": "fg",
    "size": 20,
    "shipment": "6412097ce444f65477d71f25",
    "shade": "white",
    "annotations": "Very new",
    "bf": 22,
    "sold": false,
    "soldTo": ""
}

# ---------------------------------------
# POST reels

###
#This should work
POST http://localhost:3001/api/reels HTTP/1.1
content-type: application/json

[
    {
        "gsm": 120,
        "size": 20,
        "shipment": "6412097ce444f65477d71f25",
        "shade": "white",
        "annotations": "Very new",
        "bf": 22,
        "sold": false,
        "soldTo": ""
    },
    {
        "gsm": 120,
        "size": 20,
        "shipment": "6412097ce444f65477d71f25",
        "shade": "white",
        "annotations": "Very new",
        "bf": 22,
        "sold": false,
        "soldTo": "" 
    }
]

###
#This should not work
POST http://localhost:3001/api/reels HTTP/1.1
content-type: application/json

[
    {
        "gsm": "[]",
        "size": 20,
        "shipment": "6412097ce444f65477d71f25",
        "shade": "white",
        "annotations": "Very new",
        "bf": 22,
        "sold": false,
        "soldTo": ""
    },
    {
        "gsm": 120,
        "size": 20,
        "shipment": "6412097ce444f65477d71f25",
        "shade": "white",
        "annotations": "Very new",
        "bf": true,
        "sold": "gggg",
        "soldTo": ""
    }
]

# ---------------------------------------
# DELETE reel

###
#This should work
DELETE http://localhost:3001/api/reel/64299eeda898561ddadde23b HTTP/1.1

###
#This should not work
DELETE http://localhost:3001/api/reel/eeda898561ddadde23b HTTP/1.1

# ---------------------------------------
# DELETE reels

###
#This should work
DELETE http://localhost:3001/api/reels?ids=64247fc34f652067173bc086,64299c60756175da89ac54ec HTTP/1.1

###
#This should not work
DELETE http://localhost:3001/api/reels?ids=642c91ceb497b0ab40870eae HTTP/1.1

# ---------------------------------------
# PUT reel

###
#This should work
PUT http://localhost:3001/api/reel/642c809acc4f71a6f5a1bf14 HTTP/1.1
content-type: application/json

{
    "gsm": 8
}