# ---------------------------------------
# POST reel

###
#This should work
POST http://localhost:3001/api/sheet HTTP/1.1
content-type: application/json

{
    "filters": ["6434e7b42af481de5d778565", "6434eb064e4b63b341cc80fc"],
    "shipments" :["6434eb1f4e4b63b341cc80fe", "6434f0b7d9f602918bbda32f"]
}

###

# ---------------------------------------